language: ruby
rvm:
- 2.3.1
before_install:
- export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install:
- bundle install
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source