# Site
name: "snap:bit"
title: "snap:bit"
description: "Combine BBC micro:bit with Snap Circuits"
meta_description: "Combine BBC micro:bit with Snap Circuits."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
email: 'kaloyan@raev.name'
# TODO
#google_analytics: ''

collections:
  projects:
    output: true
    permalink: /:collection/:title.html

# Plugins
plugins: 
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
pagination:
  enabled: true
  collection: 'projects'
  per_page: 6
  permalink: '/projects/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
    
# Other
markdown: kramdown
highlighter: rouge