# Site
name: "snap:bit"
title: "snap:bit"
description: "Combine BBC micro:bit with Snap Circuits"
meta_description: "Combine BBC micro:bit with Snap Circuits."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'kaloyan@raev.name'
# TODO
#google_analytics: ''

collections:
  projects:
    output: true
    permalink: /:collection/:title.html

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
